spring:
  profiles:
    active: dev
  application:
    name: food-traceability-server

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# JWT配置
jwt:
  secret: FoodTraceBlockChainSecretKey2024FiscoProject
  expiration: 86400000  # 24小时

# 文件上传路径
file:
  upload-path: ./uploads/

# 日志配置
logging:
  level:
    com.trace: debug
    com.baomidou: debug
    org.fisco.bcos: info

# FISCO BCOS 区块链配置
blockchain:
  enabled: true
  mock-mode: true   # true=模拟模式(开发用), false=连接真实链
  config-path: classpath:fisco-config.toml
  group-id: 1
  # TODO: 以下两项部署合约后手动填入
  contract-address: "0xdd2a54c360a48350b75ccae25351d93caec4aa52"
  private-key: "4b31de1828883e36cdcc50a15a2f82188b8aec11adc43c11fd648012d9e7c5ad"

