spring:
  profiles:
    active: dev
  application:
    name: agri-traceability-server

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

